@echo off
cls
echo.
echo  IMPORTANT INFO
echo ====================
echo.
echo    If you ae installing Avix 486 off the Floppy Disk, then
echo    you need to copy the files onto your Hard Drive. 
echo.
echo  *You might want to use XCopy to do this
echo.
echo    When the files are finished being copied to your Hard 
echo    Drive, type "486" to install Avix 486
echo.
echo  USING XCOPY
echo ===============                                   
echo.
echo  *You need MS-DOS 5.0 or later
echo.
echo    1) Make sure you are on the (C:) Drive
echo.
echo    2) Type "XCOPY A:" and let it copy the files
echo. 